# Generated by Django 3.2.7 on 2021-10-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('-balance',)},
        ),
    ]
