# Generated by Django 3.2.6 on 2021-08-10 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='admin',
            field=models.OneToOneField(help_text='Club admin id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Name of the club', max_length=255),
        ),
    ]
