# Generated by Django 3.2.6 on 2021-09-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_commission',
            field=models.FloatField(default=2),
        ),
    ]
