# Generated by Django 3.2.6 on 2021-08-11 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210810_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Club's current balance.", max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
