# Generated by Django 3.2.6 on 2021-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_editor',
            field=models.BooleanField(default=False),
        ),
    ]
