# Generated by Django 3.2.6 on 2021-08-13 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_club_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='balance',
            field=models.FloatField(default=0, help_text="Club's current balance.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, help_text='Users current balance. ', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
