# Generated by Django 3.2.6 on 2021-08-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='user_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
