# Generated by Django 3.2.7 on 2021-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
