# Generated by Django 3.2.6 on 2021-08-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configmodel',
            options={'ordering': ('name',), 'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
    ]
