# Generated by Django 3.2.6 on 2021-08-10 01:21

import betting.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AlterModelOptions(
            name='betscope',
            options={'ordering': ['-end_time']},
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_scope',
            field=models.ForeignKey(help_text='For which question bet is done', on_delete=django.db.models.deletion.PROTECT, to='betting.betscope', validators=[betting.models.bet_scope_validator]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4')], help_text='List of bet choices', max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(default='No result', help_text='Result of the bet. Win/Loss', max_length=255),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(help_text='User id who betting', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='end_time',
            field=models.DateTimeField(help_text='when this question will no longer accept bet'),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='locked',
            field=models.BooleanField(default=False, help_text='manually lock question before end_time'),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='match',
            field=models.ForeignKey(help_text='Id of the match under which this is question', on_delete=django.db.models.deletion.CASCADE, to='betting.match'),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='question',
            field=models.CharField(help_text='Question of bet', max_length=1023),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='start_time',
            field=models.DateTimeField(help_text='when this question will be available for bet'),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='winner',
            field=models.CharField(blank=True, choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4')], help_text='Which option is the winner. Be careful. As soon as you select winner, bet winner receive money. This can not be reverted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='depositwithdrawmethod',
            name='code',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('surecash', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], help_text='hidden method code for internal processing', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='depositwithdrawmethod',
            name='name',
            field=models.CharField(help_text='Method name to be shown to users', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(help_text='When match will be locked for betting.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_name',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('tennis', 'Tennis'), ('others', 'Others')], help_text='name of the game', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(help_text='When match will be unlocked for betting.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(help_text='title of the match. eg: Canada vs USA', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(blank=True, help_text='bank account number. Used for deposit and withdraw', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='how much money transacted in 2 point precession decimal number', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('surecash', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('bet', 'Bet'), ('bet_odd', 'Odd bet id'), ('bet_even', 'Even bet id'), ('transfer', 'Transfer')], help_text='method used to do transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_internally',
            field=models.BooleanField(default=False, editable=False, help_text='For internal uses only'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.ForeignKey(blank=True, help_text='User id to whom money transferred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction id, used for only deposit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal')], help_text='type of transaction, withdraw or deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='User id of transaction maker', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(default=False, help_text='Status if admin had verified. After verification(for deposit), user account will be deposited'),
        ),
    ]
