# Generated by Django 3.2.6 on 2021-08-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
