# Generated by Django 3.2.6 on 2021-08-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-end_time', '-start_time', 'name', 'option_1', 'option_2']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='draw_ratio',
            new_name='draw_rate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='first',
            new_name='option_1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='first_ratio',
            new_name='option_1_rate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='second',
            new_name='option_2',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='second_ratio',
            new_name='option_2_rate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.CharField(choices=[('option_1', 'Option 1'), ('draw', 'Draw'), ('option_2', 'Option 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('option_1', 'Option 1'), ('draw', 'Draw'), ('option_2', 'Option 2')], max_length=10, null=True),
        ),
    ]
