# Generated by Django 3.2.6 on 2021-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20210807_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.CharField(choices=[('F', 'First'), ('D', 'Draw'), ('S', 'Second')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal')], max_length=50),
        ),
    ]
