# Generated by Django 3.2.6 on 2021-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20210906_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtransfer',
            name='amount',
            field=models.FloatField(help_text='how much money transacted in 2 point precession decimal number'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(help_text='how much money transacted in 2 point precession decimal number'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.FloatField(help_text='how much money transacted in 2 point precession decimal number'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.FloatField(help_text='how much money transacted in 2 point precession decimal number'),
        ),
    ]
