# Generated by Django 3.2.6 on 2021-08-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20210810_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwithdrawmethod',
            name='number1',
            field=models.CharField(default='017331245546', max_length=32),
        ),
        migrations.AddField(
            model_name='depositwithdrawmethod',
            name='number2',
            field=models.CharField(default='019455422145', max_length=32),
        ),
        migrations.AlterField(
            model_name='depositwithdrawmethod',
            name='code',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], help_text='hidden method code for internal processing', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('bet', 'Bet'), ('bet_odd', 'Odd bet id'), ('bet_even', 'Even bet id'), ('transfer', 'Transfer')], help_text='method used to do transaction', max_length=50),
        ),
    ]
