# Generated by Django 3.2.6 on 2021-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20211004_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='paid',
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('no result', 'No Result')], default='no result', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('no result', 'No Result')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('no result', 'No Result')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('no result', 'No Result')], default='pending', max_length=20),
        ),
    ]
