# Generated by Django 3.2.6 on 2021-08-14 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_match_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betscope',
            name='option_1_rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='option_2_rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='option_3_rate',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='option_4_rate',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
