# Generated by Django 3.2.6 on 2021-08-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20210810_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositwithdrawmethod',
            name='number1',
            field=models.CharField(blank=True, default='017331245546', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='depositwithdrawmethod',
            name='number2',
            field=models.CharField(blank=True, default='019455422145', max_length=32, null=True),
        ),
    ]
