# Generated by Django 3.2.6 on 2021-10-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20211004_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='user_balance',
            new_name='balance',
        ),
    ]
