# Generated by Django 3.2.6 on 2021-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_clubtransfer_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.CharField(choices=[('refer', 'Refer commission'), ('club', 'Club commission')], default='refer', max_length=255),
            preserve_default=False,
        ),
    ]
