# Generated by Django 3.2.6 on 2021-08-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20210818_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('transfer', 'Transfer'), ('club', 'Club W/D')], help_text='method used to do transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('transfer', 'Transfer'), ('club', 'Club W/D')], help_text='method used to do transaction', max_length=50),
        ),
    ]
