# Generated by Django 3.2.7 on 2021-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20211006_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(default='Not Defined', max_length=255),
        ),
    ]
