# Generated by Django 3.2.6 on 2021-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20210807_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pending',
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
