# Generated by Django 3.2.6 on 2021-09-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('betting', '0004_commission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commission',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.club'),
        ),
    ]
