# Generated by Django 3.2.6 on 2021-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20210807_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
