# Generated by Django 3.2.6 on 2021-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20210818_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='betscope',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
