# Generated by Django 3.2.6 on 2021-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20210810_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='superuser_account',
            field=models.CharField(blank=True, help_text='bank account number of the superuser', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction id from bank when sent money', max_length=255, null=True),
        ),
    ]
