# Generated by Django 3.2.6 on 2021-09-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_auto_20210902_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
