# Generated by Django 3.2.7 on 2021-10-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_rename_hide_match_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betquestion',
            old_name='hide',
            new_name='hidden',
        ),
    ]
