# Generated by Django 3.2.6 on 2021-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_auto_20210811_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betscope',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='when this question will no longer accept bet', null=True),
        ),
        migrations.AlterField(
            model_name='betscope',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='when this question will be available for bet', null=True),
        ),
    ]
