# Generated by Django 3.2.6 on 2021-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.CharField(choices=[('first', 'First'), ('draw', 'Draw'), ('second', 'Second')], max_length=10),
        ),
    ]
