# Generated by Django 3.2.7 on 2021-10-05 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_rename_hide_betquestion_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='title',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_name',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_name',
            field=models.CharField(default='B', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
