# Generated by Django 3.2.6 on 2021-08-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0006_alter_bet_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed_internally',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
