# Generated by Django 3.2.7 on 2021-10-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_auto_20211005_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='match',
            name='live',
        ),
        migrations.RemoveField(
            model_name='match',
            name='locked',
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('hidden', 'Hidden'), ('closed', 'Closed'), ('locked', 'Locked')], default='hidden', max_length=255),
        ),
    ]
