# Generated by Django 3.2.6 on 2021-08-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_alter_transaction_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betscope',
            options={'ordering': ['-end_time'], 'verbose_name_plural': 'Bet Options'},
        ),
        migrations.AlterModelOptions(
            name='depositwithdrawmethod',
            options={'verbose_name': 'Method', 'verbose_name_plural': 'Method List'},
        ),
    ]
