# Generated by Django 3.2.7 on 2021-10-05 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_auto_20211005_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betquestion',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bet Options'},
        ),
        migrations.RemoveField(
            model_name='betquestion',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='betquestion',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='betquestion',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='betquestion',
            name='paid',
        ),
        migrations.AddField(
            model_name='betquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betquestion',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('hidden', 'Hidden'), ('closed', 'Closed'), ('locked', 'Locked')], default='hidden', max_length=255),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='limit',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='betquestion',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.match'),
        ),
    ]
