# Generated by Django 3.2.6 on 2021-08-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_auto_20210807_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['game', '-created_at']},
        ),
    ]
