# Generated by Django 3.2.6 on 2021-08-13 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0009_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('bet', 'Bet'), ('bet_odd', 'Odd bet id'), ('bet_even', 'Even bet id'), ('transfer', 'Transfer'), ('club', 'Club withdraw')], help_text='method used to do transaction', max_length=50)),
                ('amount', models.FloatField(help_text='how much money transacted in 2 point precession decimal number', validators=[django.core.validators.MinValueValidator(1)])),
                ('account', models.CharField(blank=True, help_text='bank account number. Used for deposit and withdraw', max_length=255, null=True)),
                ('superuser_account', models.CharField(blank=True, help_text='bank account number of the superuser', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=None, help_text='Status if admin had verified. After verification(for deposit), user account will be deposited', null=True)),
                ('processed_internally', models.BooleanField(default=False, editable=False, help_text='For internal uses only')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='User id of transaction maker', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='how much money transacted in 2 point precession decimal number', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False, help_text='Status if admin had verified. After verification(for deposit), user account will be deposited')),
                ('processed_internally', models.BooleanField(default=False, editable=False, help_text='For internal uses only')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('to', models.ForeignKey(blank=True, help_text='User id to whom money transferred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User id of transaction maker', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('bet', 'Bet'), ('bet_odd', 'Odd bet id'), ('bet_even', 'Even bet id'), ('transfer', 'Transfer'), ('club', 'Club withdraw')], help_text='method used to do transaction', max_length=50)),
                ('amount', models.FloatField(help_text='how much money transacted in 2 point precession decimal number', validators=[django.core.validators.MinValueValidator(1)])),
                ('account', models.CharField(blank=True, help_text='bank account number. Used for deposit and withdraw', max_length=255, null=True)),
                ('superuser_account', models.CharField(blank=True, help_text='bank account number of the superuser', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=None, help_text='Status if admin had verified. After verification(for deposit), user account will be deposited', null=True)),
                ('processed_internally', models.BooleanField(default=False, editable=False, help_text='For internal uses only')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='User id of transaction maker', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
