# Generated by Django 3.2.6 on 2021-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_alter_bet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('draw', 'Draw'), ('second', 'Second')], max_length=10, null=True),
        ),
    ]
