# Generated by Django 3.2.7 on 2021-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_auto_20211006_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert_rate', models.FloatField(default=1.0)),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], max_length=255)),
                ('method_type', models.CharField(choices=[('personal', 'Personal'), ('agent', 'Agent')], default='personal', max_length=255)),
                ('number1', models.CharField(max_length=32)),
                ('number2', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Method List',
            },
        ),
        migrations.DeleteModel(
            name='DepositWithdrawMethod',
        ),
    ]
