# Generated by Django 3.2.6 on 2021-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0010_auto_20210813_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
