# Generated by Django 3.2.7 on 2021-10-06 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211005_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0010_auto_20211006_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='deposit',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.club'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('transfer', 'Transfer'), ('club', 'Club W/D'), ('commission', 'Commission'), ('refer', 'Referral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='site_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
