# Generated by Django 3.2.6 on 2021-08-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0010_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='processed_internally',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
