# Generated by Django 3.2.7 on 2021-10-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0011_auto_20211006_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='transaction_id',
            new_name='reference',
        ),
    ]
