# Generated by Django 3.2.6 on 2021-08-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0012_auto_20210808_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWithdrawMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('bet', 'Bet'), ('transfer', 'Transfer money'), ('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('surecash', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bet', 'Bet'), ('transfer', 'Transfer money'), ('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('surecash', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], max_length=50),
        ),
    ]
