# Generated by Django 3.2.6 on 2021-08-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0012_alter_transfer_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='to',
            field=models.ForeignKey(help_text='User id to whom money transferred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
