# Generated by Django 3.2.7 on 2021-10-06 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0012_rename_transaction_id_withdraw_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='questionoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay'), ('transfer', 'Transfer'), ('club', 'Club W/D'), ('commission', 'Commission'), ('refer', 'Referral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='site_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
