# Generated by Django 3.2.6 on 2021-08-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0013_auto_20210808_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositwithdrawmethod',
            name='code',
            field=models.CharField(choices=[('bet', 'Bet'), ('transfer', 'Transfer money'), ('bkash', 'bKash'), ('rocket', 'DBBL Rocket'), ('surecash', 'Nagad'), ('upay', 'Upay'), ('mcash', 'Mcash'), ('mycash', 'My Cash'), ('surecash', 'Sure Cash'), ('trustpay', 'Trust Axiata Pay')], max_length=255, unique=True),
        ),
    ]
